(define (e14)
  (define memo (make-hash-table))
  (define (chain-length n)
    (unless (hash-table-exists? memo n)
      (hash-table-put! memo n (+ 1 (chain-length (if (even? n) (/ n 2) (+ (* 3 n) 1))))))
    (hash-table-get memo n))
  (hash-table-put! memo 1 1)
  (fold (^(n p) (if (> (chain-length n) (chain-length p)) n p))
        1 (iota 1000000 1)))
