;; Gauche 0.9.3

(add-load-path "." :relative)
(use eulerlib)

(define (e75)
  (let* ((lim 1500000)
	 (triangles (make-vector (+ lim 1) 0))
	 (m-lim (floor->exact (sqrt (/ lim 2)))))
    (dolist (m (range 2 m-lim))
      (dolist (n (range 1 m))
	(when (and (= 1 (modulo (+ n m) 2))
		   (= 1 (gcd n m)))
	  (let1 L (+ (- (* m m) (* n n))
		     (* 2 m n)
		     (+ (* m m) (* n n)))
	    (when (<= L lim)
	      (dolist (l (range L lim L))
		(vector-set! triangles l (+ 1 (vector-ref triangles l)))))))))
    (length (filter (cut = 1 <>)
		    (vector->list triangles)))))